### ISSUE TITLE
Download page refinements

### ISSUE THREAD

**Issue by pchote** [Fauntleroy/openra-web#4]
* The licensing text on the current website has been updated, and it is a requirement from EA that the non-endorsement statement is near the top of the page (I imagine there is a bit of flexibility here wrt page headers etc, but it certainly needs to be above the download links). IMO the best solution here is to move the "License and Game Assets" section between the download platform buttons and the platform instructions, reducing the margins between the three sections (and IMO removing the horizontal rules, which tbh i'm not a fan of design-wise) to avoid pushing the instructions too far below the fold.
* IMO it looks unbalanced to have the Release and Playtest download buttons with different widths, and the AppImage download buttons in particular look odd with 6 different sizes! Can we please use a fixed width for all of these?
* The Windows instructions is missing the "Installers for 32-bit Windows can be found in the [GitHub Releases] archive." line from the current website.
* The macOS instructions are out of date (the current release is notarized), and will be changing again for the next release. Can we change the top line to say "OpenRA works best on a mac running macOS 10.13 or later." and then add a line below the download buttons (but above the Cask section) with "A separate "compat" release for OS X 10.9 – 10.12 can be found in the [GitHub Releases] archive."
* The Exherbo, Gentoo, nix, and Slackware downstream builds are no longer maintained and have been removed from the current website. They should be removed on the new version too.
* IMO it would be good if we could keep the external package warning distinct from the other page text by adjusting its size/itallics/colour, and we could maybe add a ⚠️  glyph?
* I understand the motivation for wanting to put the download links as high up the page as possible, but it feels wrong to have the description about playtest versus release builds at the bottom of the page - players need to understand this in order to know what build to download.

**Comment by takempf** [comment]
@pchote I've addressed these issues in a smattering of recent commits. Please take a look at https://openra.kempf.dev/download and let me know what you think!

**Comment by pchote** [comment]
There are a few small wording complaints that i'll follow up on with proper suggestions later, but I think the overall page structure now works quite well 👍

**Comment by pchote** [comment]
Here are my detailed nits, sorry for the delay!

* I'm not a fan of the top description line: "OpenRA engine" isn't really correct (since the downloads here are for the default mods), and IMO its redundant to list OSes again when we have prominant icons below. If we need something here to make the page layout work, how about "The latest stable release is release-20200503, and the latest playtest is playtest-20201213." like on the current page?
* Windows Tab:
   * "OpenRA works on most computers running Windows 7 or later that support DirectX 11 or OpenGL 3+". 
   * We can probably remove the line about drivers since i believe DX drivers come with windows(?)
   * We have just started packaging portable downloads too, so it would be good  to mention them. Can we change the bottom line to "32-bit installers and portable releases can be downloaded from the [release-2020503](https://github.com/OpenRA/OpenRA/releases/tag/release-20200503) and [playtest-20201213](https://github.com/OpenRA/OpenRA/releases/tag/playtest-20201213) archives." where the tag names are automatically populated? If no playtests are available this should shorten to "32-bit installers and portable releases can be downloaded from the [release-2020503](https://github.com/OpenRA/OpenRA/releases/tag/release-20200503) archive."
 * macOS tab:
    * IMO the color of the info icon in whatever font my browser is using (might be different for others?) and the light blue text looks out of place with the rest of the page. Lets stick with white and no logo.
    * We could change the info line to match my suggestion on the windows tab: "A "compat" version supporting OS X 10.9 – 10.12 can be downloaded from the [release-2020503](https://github.com/OpenRA/OpenRA/releases/tag/release-20200503) and [playtest-20201213](https://github.com/OpenRA/OpenRA/releases/tag/playtest-20201213) archives" This annoyingly wraps past one line when I tried editing it live, but I can't think of a way to reduce the sentence length without hurting readability. Maybe we could reduce the font size a bit to solve this and also distinguish these info lines from the main copy?
* Linux tab:
  * We should have the "We do not maintain this external package source..." message at the end of the "Community Maintained Packages" paragraph
 * FreeBSD tab:
    * "FreeBSD Ports Collection" has lost its hyperlink
 * Source code tab:
   * Remove the (leftover from a previous version?) header that doesn't match the other tabs

**Comment by takempf** [comment]
The requested changes have been made, including the dynamic elements (which should work just fine). 

https://openra.kempf.dev/download

**Comment by pchote** [comment]
Looks great!

I just noticed one last thing, for some reason the source code description (on the current website, not your fault) is linking to an outdated wiki page instead of our proper installation instructions. Can we please change it to

> Compilation instructions are available for [release-20200503](https://github.com/OpenRA/OpenRA/blob/release-20200503/INSTALL.md) and [playtest-20201213](https://github.com/OpenRA/OpenRA/blob/playtest-20201213/INSTALL.md).

note: more dynamic links to be set based on tag/playtest availability...

**Comment by pchote** [comment]
Can you please also add the new OpenSUSE and WinGet instructions that @mailaender added in https://github.com/OpenRA/OpenRAWeb/pull/501?

**Comment by Mailaender** [comment]
You removed some links at https://openra.kempf.dev/download For @openSUSE that one is important as it isn't in the default repo.

**Comment by takempf** [comment]
I've made a couple updates which should resolve the outstanding issues in this thread: https://openra.kempf.dev/download#linux

**Comment by pchote** [comment]
Platform buttons seem to have regressed for me:

![Screenshot 2021-01-14 at 09 31 38](https://user-images.githubusercontent.com/167819/104571756-627fa300-564b-11eb-90c5-d7edd42a922e.png)
