### ISSUE TITLE
About page refinements

### ISSUE THREAD

**Issue by pchote** [Fauntleroy/openra-web#7]
I really like what you've done here overall, just a couple of wording tweaks and an idea that may not be worth the trouble:

- [x] Add the "EA has not endorsed and does not support this product." disclaimer as a new paragraph below the description to the left of the trailer.
- [x] The wording of the trailer description feels wrong, IMO. Would it be bad to repeat "OpenRA 10th Anniversary Trailer (2017)"?
- [x] The wording below "The OpenRA Games" header doesn't quite send the right message IMO. I suggest something along the lines of "Games built using the OpenRA engine are known as “mods”. The OpenRA development team maintain the three official mods that can be [downloaded from this website](https://www.openra.net/download/), but many more are developed and maintained by the OpenRA community." The "downloaded from this website" wording doesn't feel quite right, but i can't think of something better right now.
- [x] The "Under Construction" banner feels disproportionately bold IMO. I think it would look better if we could reduce the vertical padding so there is less yellow.
- [x] IMO we should change the custom mod image description to not wrap onto a second line. How about "Community mods can be found through ModDB"?
- [ ] I had an idea that might make the mod images look better: how hard would it be to crop the top/bottom edges (so they occupy more of the width of the page) and then fade the edge closest to the text to black? IMO this might look better than the current hard edge.

**Comment by takempf** [comment]
@pchote pushed up a commit that handles most of these complaints. I'm not very keen on adding "fade out" edges to the images, so I'm going to push back on that a bit. Here are my scattered thoughts on it:

- The images actually sit on a transparent background, so I'd need to make them all PNGs or use some kind of (not browser compatible) masking to get it to work "properly"
- The images seem fine to me, and I'd bet interested in knowing what bothers you about them
- This is mostly just an adaptation of the content that's currently on the website. As I come to understand the project better over time, I come up with better ideas. I think there is a more cohesive, site-wide kind of content change that could better serve the objectives this page tries to meet. For instance, a focus on the OpenRA Engine project, that splits off into pages/subsites/sections that describe each mod's project. Which is to say, this page will ideally go through a pretty big evolution, or even be discarded (for something better) in the future.

**Comment by pchote** [comment]
No worries. I knew that idea might be controversial, which is why I posed it as a question rather than a request.

The about page looks great now, so I consider this issue solved :+1:
